#!/bin/bash
#Star User Set-up

set -e

if [ ! -d "/home/$USER/.config/star" ]; then
	mkdir /home/$USER/.config/star
fi

if [ ! -f "/home/$USER/.config/star/star-setup" ]; then

    # if [ -f "/home/$USER/.fluxbox/init" ]; then
    #     rpl -q 'REPLACEME' $USER /home/$USER/.fluxbox/init > /dev/null 2>&1
    # fi
    if [ -f "/home/$USER/.gtkrc-2.0" ]; then
        rpl -q 'REPLACEME' $USER /home/$USER/.gtkrc-2.0 > /dev/null 2>&1
    fi
    if [ -f "/home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js" ]; then
        rpl -q 'REPLACEME' $USER /home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js > /dev/null 2>&1
    fi
    
    ln -s /usr/share/backgrounds /home/$USER/images/wallpapers/shared

	if [ "$USER" != "starlive" ]; then
		sed -i".bak" '/# installer start/,/# installer end/d' /etc/skel/.config/i3/config
		rm /etc/skel/.config/i3/config.bak
		if [ -f "/home/$USER/.config/i3/config" ]; then
			rm /home/$USER/.config/i3/config
		fi
		if [ -f "/home/$USER/.config/conky/conky_shortcuts_live_grey" ]; then
			rm /home/$USER/.config/conky/conky_shortcuts_live_grey
		fi
		cp /etc/skel/.config/i3/config /home/$USER/.config/i3/config
		cp /etc/skel/.config/conky/conky_shortcuts_live_grey2 /home/$USER/.config/conky/conky_shortcuts_live_grey
	fi
	
	touch /home/$USER/.config/star/star-setup
    chown -R $USER:$USER /home/$USER

fi

xdg-user-dirs-update

exit 0
