#!/bin/bash

submanual(){
while :
do
echo "sub Menu:"
echo -e "\t(x) Options 1"
echo -e "\t(y) Options 1"
echo -e "\t(e) Back"
echo -n "Please enter your choice:"
read c
case $c in
    "x"|"X")
    # Options 1 and its commands
    ;;
    "y"|"Y")
    # Options 2 and its commands
    ;;
    "e"|"E")
    break
    ;;
        *)
        echo "invalid answer, please try again"
        ;;
esac
done
}

while :
do
echo "Main Menu:"
echo -e "\t(a) More Menu Options "
echo -e "\t(q) Exit"
echo -n "Please enter your choice:"
read choice
case $choice in
    "a"|"A")
    submanual
    ;;
    "q"|"Q")
    exit
    ;;
        *)
        echo "invalid answer, please try again"
        ;;

esac
done
