#!/bin/bash
#Star User Set-up

set -e

USER=$1

if [ ! -d "/home/$USER/.config/star" ]; then
	mkdir /home/$USER/.config/star
fi

if [ ! -f "/home/$USER/.config/star/star-setup" ]; then

    #cd /etc/skel
    #tar cpzf skel.tar.gz .
    #mv skel.tar.gz /home/$USER/skel.tar.gz
    #cd /home/$USER
    #tar xkpsf skel.tar.gz
    #rm skel.tar.gz

    if [ -f "/home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js" ]; then
        rpl -q 'REPLACEME' $USER /home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js > /dev/null 2>&1
    fi

    ln -s /usr/share/backgrounds /home/$USER/images/wallpapers/shared

    if [ "$USER" != "starlive" ]; then
		sed -i".bak" '/<!-- installer start -->/,/<!-- installer end -->/d' /etc/skel/.jwmrc
		rm /etc/skel/.jwmrc.bak
		if [ -f "/home/$USER/.jwmrc" ]; then
			rm /home/$USER/.jwmrc
		fi
		cp /etc/skel/.jwmrc /home/$USER/.jwmrc
	fi

	touch /home/$USER/.config/star/star-setup
    chown -R $USER:$USER /home/$USER
fi

xdg-user-dirs-update

exit 0
