#!/bin/sh

set -e

DISTRIBUTION="jessie"
ARCHITECTURES="amd64"
LINUX_FLAVOURS="amd64"
ARCHIVE_AREAS="main contrib non-free"
SOURCE="false"
MIRROR_BINARY="http://packages.devuan.org/merged"

# --debootstrap-options "--variant=minbase" \
# 	--initramfs-compression lzma \

lb config noauto \
	--mode "devuan" \
	--chroot-filesystem "squashfs" \
	--debootstrap-options "--variant=minbase" \
	--distribution "${DISTRIBUTION}" \
	--debian-installer-distribution "${DISTRIBUTION}" \
	--debian-installer "live" \
	--architectures "${ARCHITECTURES}" \
	--linux-flavours "${LINUX_FLAVOURS}" \
	--apt-recommends "false" \
	--apt-source-archives 'false' \
	--apt-indices "false" \
	--archive-areas "${ARCHIVE_AREAS}" \
	--firmware-chroot "false" \
	--parent-mirror-bootstrap "${MIRROR_BINARY}" \
	--parent-mirror-binary "${MIRROR_BINARY}" \
	--mirror-bootstrap "${MIRROR_BINARY}" \
	--mirror-binary "${MIRROR_BINARY}" \
	--backports "false" \
	--security "false" \
    --updates "false" \
    --firmware-chroot "false" \
	--memtest "none" \
	--win32-loader "false" \
	--debug \
	--verbose \
	--source "false" \
	--bootappend-live "boot=live config components file=/preseed.cfg quiet splash noautologin nouveau.modeset=0 radeon.modeset=0" \
"${@}"

# lb config --apt-indices false --apt-recommends false --debootstrap-options "--variant=minbase" --firmware-chroot false --memtest none
