#!/bin/sh

set -e

DISTRIBUTION="jessie"
ARCHITECTURES="amd64"
LINUX_FLAVOURS="amd64"
ARCHIVE_AREAS="main"
SOURCE="false"
MIRROR_BINARY="http://packages.devuan.org/merged"

# --debootstrap-options "--variant=minbase" \
#	--debian-installer-gui false \
#	--firmware-chroot false \
#	--debian-installer-distribution "${_DISTRIBUTION}" \
#	--debian-installer live \
# 	--initramfs-compression lzma \

lb config noauto \
	--mode devuan \
	--chroot-filesystem squashfs \
	--distribution "${_DISTRIBUTION}" \
	--debian-installer-distribution "${_DISTRIBUTION}" \
	--debian-installer live \
	--architectures "${_ARCHITECTURES}" \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--apt-recommends false \
	--apt-secure true \
	--apt-indices false \
	--apt-source-archives false \
	--archive-areas "${_ARCHIVE_AREAS}" \
	--parent-mirror-bootstrap "${_MIRROR_BINARY}" \
	--parent-mirror-binary "${_MIRROR_BINARY}" \
	--mirror-bootstrap "${_MIRROR_BINARY}" \
	--mirror-binary "${_MIRROR_BINARY}" \
	--iso-application "Star Linux" \
	--iso-publisher "Star" \
	--iso-volume "Star Live" \
	--backports false \
	--security false \
    --updates false \
	--memtest none \
	--win32-loader false \
	--debug \
	--verbose \
"${@}"

# lb config --apt-indices false --apt-recommends false --debootstrap-options "--variant=minbase" --firmware-chroot false --memtest none
