#! /bin/sh
### BEGIN INIT INFO
# Provides:          udev-persistent-net-rules-remover
# Required-Start:    
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Remove stored udev persistent net rules
# Description:       Each time system stop, remove the udev net rules
#                    persistence file from /etc/udev/rules.d/*persistent-net.rules
### END INIT INFO
#
# Author:	Gregory DAVID <dev@groolot.net>
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin

case "$1" in
    start)
	;;
    stop)
	rm -f /etc/udev/rules.d/*persistent-net.rules >/dev/null 2>&1
	;;
    force-reload|restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: /etc/init.d/udev-persistent-net-rules-remover {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
